get_clients:
    pattern: /clients
    defaults: { _controller: VieilleSardineUserBundle:User:getUsers }
    
send_mail:
    pattern: /send_mail/{name}
    defaults: { _controller: VieilleSardineUserBundle:Mail:sendMail }