Produit:
    type: entity
    table: produit
    fields:
        idProduit:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_produit
            generator:
                strategy: IDENTITY
        titre:
            type: string
            length: 100
            fixed: false
            nullable: false
        description:
            type: text
            nullable: false
        prixHt:
            type: float
            nullable: false
            column: prix_ht
        prixTtc:
            type: float
            nullable: false
            column: prix_ttc
        statut:
            type: boolean
            nullable: false
        tva:
            type: float
            nullable: false
        poids:
            type: float
            nullable: false
        hauteur:
            type: float
            nullable: false
        largeur:
            type: float
            nullable: false
        longueur:
            type: float
            nullable: false
        reference:
            type: string
            length: 10
            fixed: false
            nullable: false
    manyToMany:
        idCoffret:
            targetEntity: Coffret
            cascade: {  }
            mappedBy: idProduit
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
