parameters:
#    vieille_sardine_stock.example.class: VieilleSardine\StockBundle\Example

services:
#    vieille_sardine_stock.example:
#        class: %vieille_sardine_stock.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
