vieille_sardine_catalogue:
    resource: "@VieilleSardineCatalogueBundle/Resources/config/routing.yml"
    prefix:   /catalogue/

vieille_sardine_retour:
    resource: "@VieilleSardineRetourBundle/Resources/config/routing.yml"
    prefix:   /retour/

vieille_sardine_stock:
    resource: "@VieilleSardineStockBundle/Resources/config/routing.yml"
    prefix:   /stock/

vieille_sardine_paiement:
    resource: "@VieilleSardinePaiementBundle/Resources/config/routing.yml"
    prefix:   /paiment/

vieille_sardine_produit:
    resource: "@VieilleSardineProduitBundle/Resources/config/routing.yml"
    prefix:   /produit/

vieille_sardine_livraison:
    resource: "@VieilleSardineLivraisonBundle/Resources/config/routing.yml"
    prefix:   /livraison

vieille_sardine_panier:
    resource: "@VieilleSardinePanierBundle/Resources/config/routing.yml"
    prefix:   /panier

vieille_sardine_user:
    resource: "@VieilleSardineUserBundle/Resources/config/routing.yml"
    prefix:   /user/
    
vieille_sardine_commande:
    resource: "@VieilleSardineCommandeBundle/Resources/config/routing.yml"
    prefix:   /commande/
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile