parameters:
#    vieille_sardine_retour.example.class: VieilleSardine\RetourBundle\Example

services:
#    vieille_sardine_retour.example:
#        class: %vieille_sardine_retour.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
