Client\UserBundle\Entity\Client:
    type: entity
    table: client
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 20
            fixed: false
            nullable: false
        dateCreate:
            type: datetime
            nullable: false
            column: date_create
#        password:
#            type: blob
#            nullable: false
    lifecycleCallbacks: {  }
