parameters:
#    vieille_sardine_produit.example.class: VieilleSardine\ProduitBundle\Example

services:
#    vieille_sardine_produit.example:
#        class: %vieille_sardine_produit.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
