vieille_sardine_commande_homepage:
    pattern:  /
    defaults: { _controller: VieilleSardineCommandeBundle:Commande:index }

#clients_list:
#    pattern: /clients
#    defaults: { _controller: VieilleSardineUserBundle:User:getUsers }

ajout_produit_commande_vpc:
    pattern:  /ajoutProduit
    defaults: { _controller: VieilleSardineCommandeBundle:Commande:CreerFormVPC }

commande_groupee:
    pattern: /commandeGroupe
    defaults: { _controller: VieilleSardineCommandeBundle:CommandeGroupe:index }

service_VPC:
	pattern: /serviceVPC
	defaults: { _controller: VieilleSardineCommandeBundle:Commande:menuVPC }