parameters:
#    vieille_sardine_commande.example.class: VieilleSardine\CommandeBundle\Example

services:
#    vieille_sardine_commande.example:
#        class: %vieille_sardine_commande.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
